version: '3.2'

services:
  caddy:
    image: abiosoft/caddy
    restart: "no"
    volumes:
      - caddy_data:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile:ro
    ports:
      - mode: host # mode:host required to get correct client ip from docker swarm
        protocol: tcp
        published: "${RPNOW_PORT-80}"
        target: 80
      - mode: host # mode:host required to get correct client ip from docker swarm
        protocol: tcp
        published: "${RPNOW_SSL_PORT-443}"
        target: 443
    networks:
      - front-layer
    # http2 is off because... no websockets in http2!
    command: ["-agree", "-conf", "/etc/Caddyfile", "-http2=false", "-ca", "${ACME_CA-https://acme-v02.api.letsencrypt.org/directory}"]
    deploy:
      placement:
        constraints: [node.role == manager]

  rpnow:
    image: rpnow/rpnow
    build: .
    restart: on-failure
    depends_on:
      - db
      - redis
    environment:
      RPNOW_DB_HOST: 'db'
      RPNOW_REDIS_HOST: 'redis'
      RPNOW_TRUST_PROXY: 'true'
    networks:
      - front-layer
      - back-layer
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      resources:
        limits:
          memory: 400M

  db:
    image: mongo:3.6
    restart: on-failure
    volumes:
      - db_data:/data/db
    networks:
      - back-layer

  redis:
    image: redis:4-32bit # 32bit is for decreased memory usage, see docs
    restart: on-failure
    networks:
      - back-layer

networks:
  front-layer:
  back-layer:

volumes:
  caddy_data:
  db_data:
